# Generated by Django 3.0.8 on 2020-08-26 10:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.IntegerField(blank=True, null=True)),
                ('dcode', models.IntegerField(blank=True, null=True)),
                ('dist_name', models.CharField(blank=True, max_length=18, null=True)),
                ('shape_leng', models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True)),
                ('shape_area', models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True)),
                ('code1', models.SmallIntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=0)),
            ],
            options={
                'db_table': 'districts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='blooddata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='kapil gyawali', max_length=100)),
                ('age', models.IntegerField(default=5)),
                ('bloodgroup', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=50)),
            ],
        ),
    ]
