# Generated by Django 3.0.8 on 2020-08-31 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodshare', '0002_auto_20200826_1637'),
    ]

    operations = [
        migrations.DeleteModel(
            name='District',
        ),
    ]
