# Generated by Django 3.0.8 on 2020-08-31 08:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.IntegerField(blank=True, null=True)),
                ('dcode', models.IntegerField(blank=True, null=True)),
                ('dist_name', models.CharField(blank=True, max_length=18, null=True)),
                ('shape_leng', models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True)),
                ('shape_area', models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True)),
                ('code1', models.SmallIntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'District',
                'managed': False,
            },
        ),
    ]
